USE DB_BDD2PROYECTO1;

SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO;
SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_PREMIOS_MUNDIALES;
SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_POSICIONES_FINALES;

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.DATASET_PREMIOS_MUNDIALES;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.DATASET_PREMIOS_MUNDIALES(
    MUNDIAL             VARCHAR(25),
    LINK                VARCHAR(250),
    PREMIO              VARCHAR(30),
    JUGADOR             VARCHAR(45),
    PAIS                VARCHAR(15)
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.DATASET_POSICIONES_FINALES;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.DATASET_POSICIONES_FINALES(
    MUNDIAL   VARCHAR(max),
    POSICION  VARCHAR(max),
    SELECCION VARCHAR(max),
    ETAPA     VARCHAR(max),
    PTS       INTEGER,
    PJ        INTEGER,
    PG        INTEGER,
    PE        INTEGER,
    PP        INTEGER,
    GF        INTEGER,
    GC        INTEGER,
    DIF       INTEGER
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.DATASET_TRESULTADOS_PARTIDO;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.DATASET_TRESULTADOS_PARTIDO(
    MUNDIAL         VARCHAR(250) NOT NULL DEFAULT '',
    ETAPA           VARCHAR(250) NOT NULL DEFAULT '',
    RESULTADO       VARCHAR(250) NOT NULL DEFAULT '',
    EQUIPO1         VARCHAR(250) NOT NULL DEFAULT '',
    EQUIPO2         VARCHAR(250) NOT NULL DEFAULT '',
    FECHA           VARCHAR(250) NOT NULL DEFAULT '',
);
