--ELIMINAR LOS PROCESOS SI EXISTIERAN-----------------------------------------------------------------------------------
DROP PROCEDURE IF EXISTS TR1;
--CREAR EL PROCEDIMIENTO TR1 SIN FUNCIONALIDAD--------------------------------------------------------------------------
CREATE PROCEDURE TR1
    @AnioMundial INTEGER
AS
    PRINT 'DATOS: '+' '+@AnioMundial;
GO

--MODIFICAR EL PROCEDIMIENTO TR1 SEGUN REQUERIMIENTO--------------------------------------------------------------------
ALTER PROCEDURE TR1
    @AnioMundial INTEGER
AS
    PRINT 'DATOS: '+str(@AnioMundial);

    DECLARE @idMundial VARCHAR(50) = (SELECT MU.ID_MUNDIAL FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL MU WHERE MU.ANIO=@AnioMundial)
    BEGIN TRY
        BEGIN TRANSACTION;

            IF @idMundial IS NOT NULL
                BEGIN

                    SELECT MU.ID_MUNDIAL,MU.ANIO,MU.SELECCIONES AS CANT_PARTICIPANTES,MU.PARTIDOS AS PARTIDOS_JUGADOS,MU.GOLES AS GOLES_HECHOS FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL MU WHERE MU.ANIO=@AnioMundial;

                    SELECT PO.POSICION, EQ.NOMBRE_EQUIPO, ET.NOMBRE_ETAPA, PO.GOLES_FAVOR
                    FROM DB_BDD2PROYECTO1.PROYECTO1.POSICIONES_FINALES PO
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL MU
                    ON PO.FK_ID_MUNDIAL=MU.ID_MUNDIAL
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.EQUIPO EQ
                    ON PO.FK_ID_EQUIPO=EQ.ID_EQUIPO
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.ETAPA ET
                    ON PO.FK_ID_ETAPA=ET.ID_ETAPA
                    WHERE MU.ID_MUNDIAL=@idMundial
                    ORDER BY PO.POSICION ASC;

                    SELECT TOP 5 JU.ID_JUGADOR,JU.NOMBRE_JUGADOR,EQ.NOMBRE_EQUIPO,GOL.GOLES FROM DB_BDD2PROYECTO1.PROYECTO1.GOLEADOR GOL
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL MU
                    ON GOL.FK_ID_MUNDIAL=MU.ID_MUNDIAL
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.JUGADOR JU
                    ON GOL.FK_ID_JUGADOR=JU.ID_JUGADOR
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.EQUIPO EQ
                    ON JU.FK_ID_EQUIPO=EQ.ID_EQUIPO
                    WHERE MU.ANIO=@AnioMundial
                    ORDER BY GOL.GOLES DESC

                    SELECT JU.ID_JUGADOR,JU.NOMBRE_JUGADOR,EQ.NOMBRE_EQUIPO, TI.DESCRIPCION_PREMIO FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL MU
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.PREMIOS_MUNDIAL PR
                    ON MU.ID_MUNDIAL=PR.FK_ID_MUNDIAL
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.TIPO_PREMIO TI
                    ON PR.FK_ID_TIPO_PREMIO=TI.ID_TIPO_PREMIO
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.JUGADOR JU
                    ON PR.FK_ID_JUGADOR=JU.ID_JUGADOR
                    INNER JOIN DB_BDD2PROYECTO1.PROYECTO1.EQUIPO EQ
                    ON JU.FK_ID_EQUIPO=EQ.ID_EQUIPO
                    WHERE MU.ANIO=@AnioMundial

                END
            ELSE
                BEGIN
                    SELECT 'Lo sentimos, el mundial no existe' AS 'Mensaje'
                END

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
    END CATCH;
GO

-- PRUEBAS DE STORAGE PROCEDURE
-- EXECUTE TR1 2010; --URUGUAY

