--ELIMINAR LOS PROCESOS SI EXISTIERAN-----------------------------------------------------------------------------------
DROP PROCEDURE IF EXISTS TR2;
--CREAR EL PROCEDIMIENTO TR1 SIN FUNCIONALIDAD--------------------------------------------------------------------------
CREATE PROCEDURE TR2
    @Pais VARCHAR(100)
AS
    PRINT 'DATOS: '+' '+@Pais;
GO

--MODIFICAR EL PROCEDIMIENTO TR1 SEGUN REQUERIMIENTO--------------------------------------------------------------------
ALTER PROCEDURE TR2
    @Pais VARCHAR(100)
AS
    PRINT 'DATOS: '+' '+@Pais;

    BEGIN TRY
        BEGIN TRANSACTION;

        SELECT CAMPEON, 'GANADOR DEL MUNDIAL DEL', ANIO
        FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL WHERE CAMPEON = @Pais;

        SELECT 'EN EL MUNDIAL DE', ANIO, 'PARTICIPARON' ,SELECCIONES, 'EQUIPOS'
        FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL WHERE CAMPEON = @Pais;

        SELECT NOMBRE_JUGADOR, NUMERO_CAMISETA, POSICION, @Pais AS PAIS FROM DB_BDD2PROYECTO1.PROYECTO1.JUGADOR
        WHERE FK_ID_EQUIPO =
        (SELECT ID_EQUIPO
        FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO WHERE NOMBRE_EQUIPO = @Pais);

        SELECT POSICION, COUNT(POSICION) AS CANTIDAD FROM DB_BDD2PROYECTO1.PROYECTO1.JUGADOR
        WHERE FK_ID_EQUIPO =
        (SELECT ID_EQUIPO
        FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO WHERE NOMBRE_EQUIPO = @Pais) GROUP BY POSICION;

        SELECT COUNT(FK_ID_MUNDIAL) AS ASISTENCIAS_EN_MUNDIALES FROM DB_BDD2PROYECTO1.PROYECTO1.PARTIDO
        WHERE FK_ID_EQUIPO1 =
        (SELECT ID_EQUIPO
        FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO WHERE NOMBRE_EQUIPO = @Pais)
        OR
        FK_ID_EQUIPO2 =
        (SELECT ID_EQUIPO
        FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO WHERE NOMBRE_EQUIPO = @Pais);

        SELECT COUNT(FK_ID_MUNDIAL) AS ASISTENCIAS_EN_MUNDIALES,
               (SELECT ANIO FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL WHERE ID_MUNDIAL = PARTIDO.FK_ID_MUNDIAL) AS MUNDIAL_DE
        FROM DB_BDD2PROYECTO1.PROYECTO1.PARTIDO
        WHERE FK_ID_EQUIPO1 =
        (SELECT ID_EQUIPO
        FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO WHERE NOMBRE_EQUIPO = @Pais)
        OR
        FK_ID_EQUIPO2 =
        (SELECT ID_EQUIPO
        FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO WHERE NOMBRE_EQUIPO = @Pais)GROUP BY FK_ID_MUNDIAL;

        SELECT  @Pais, 'A PARTICIPADO EN', COUNT(*),'MUNDIALES' FROM (
        SELECT COUNT(FK_ID_MUNDIAL) AS ASISTENCIAS_EN_MUNDIALES,
               (SELECT ANIO FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL WHERE ID_MUNDIAL = PARTIDO.FK_ID_MUNDIAL) AS MUNDIAL_DE
        FROM DB_BDD2PROYECTO1.PROYECTO1.PARTIDO
        WHERE FK_ID_EQUIPO1 =
        (SELECT ID_EQUIPO
        FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO WHERE NOMBRE_EQUIPO = @Pais)
        OR
        FK_ID_EQUIPO2 =
        (SELECT ID_EQUIPO
        FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO WHERE NOMBRE_EQUIPO = @Pais)GROUP BY FK_ID_MUNDIAL)TEMP;

        SELECT POSICION,
        (SELECT ANIO FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL WHERE ID_MUNDIAL = POSICIONES_FINALES.FK_ID_MUNDIAL) AS MUNDIAL_DE
        FROM DB_BDD2PROYECTO1.PROYECTO1.POSICIONES_FINALES
        WHERE FK_ID_EQUIPO = (
        SELECT ID_EQUIPO FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO WHERE NOMBRE_EQUIPO = @Pais);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
    END CATCH;
GO

--PRUEBA---------------------------------------------------------------------
TR2 'Francia';