--ELIMINAR LOS PROCESOS SI EXISTIERAN-----------------------------------------------------------------------------------
DROP PROCEDURE IF EXISTS TR3;
--CREAR EL PROCEDIMIENTO TR1 SIN FUNCIONALIDAD--------------------------------------------------------------------------
CREATE PROCEDURE TR3
    @Jugador VARCHAR(100)
AS
    PRINT 'DATOS: '+' '+@Jugador;
GO

--MODIFICAR EL PROCEDIMIENTO TR1 SEGUN REQUERIMIENTO--------------------------------------------------------------------
ALTER PROCEDURE TR3
    @Jugador VARCHAR(100),
	@Pais_ Varchar(100)
AS
	DECLARE @Id_jugador int;
	DECLARE @Pais int;

	SELECT @Id_jugador = ID_JUGADOR, @Pais = FK_ID_EQUIPO
   FROM PROYECTO1.JUGADOR J
   INNER JOIN PROYECTO1.EQUIPO E
   ON E.NOMBRE_EQUIPO = @Pais_
   WHERE REPLACE(J.NOMBRE_JUGADOR,'_',' ') LIKE '%'+@Jugador+'%';


   SELECT NOMBRE_JUGADOR, FECHA_NACIMIENTO, POSICION,NUMERO_CAMISETA,
		LUGAR_NAC, ALTURA, APODO, WEB 
   FROM PROYECTO1.JUGADOR J
   INNER JOIN PROYECTO1.EQUIPO E
   ON E.ID_EQUIPO = @Pais
   WHERE REPLACE(J.NOMBRE_JUGADOR,'_',' ') LIKE '%'+@Jugador+'%';
   
   SELECT  ANIO AS MUNDIAL , G.GOLES, G.PARTIDOS, PROMEDIO, POSICION
   FROM PROYECTO1.GOLEADOR G
   INNER JOIN PROYECTO1.JUGADOR J
   ON G.FK_ID_JUGADOR = J.ID_JUGADOR
   AND J.ID_JUGADOR = @Id_jugador
   INNER JOIN PROYECTO1.MUNDIAL M
   ON M.ID_MUNDIAL = G.FK_ID_MUNDIAL
	
   SELECT ANIO AS MUNDIAL,P.PUNTOS, P.PARTIDOS_JUGADOS, P.PARTIDOS_EMPATADOS, P.PARTIDOS_GANADOS,P.PARTIDOS_PERDIDOS, P.GOLES_FAVOR,
   P.GOLES_CONTRA, P.DIFERENCIA_GOLES FROM PROYECTO1.MUNDIAL M
   INNER JOIN PROYECTO1.EQUIPO E
   ON M.CAMPEON = E.NOMBRE_EQUIPO AND E.ID_EQUIPO = @Pais
   inner join PROYECTO1.POSICIONES_FINALES P
   ON P.FK_ID_MUNDIAL = M.ID_MUNDIAL AND P.FK_ID_EQUIPO = @Pais

   SELECT DESCRIPCION_PREMIO, ANIO as MUNDIAL  FROM PROYECTO1.PREMIOS_MUNDIAL PM
   INNER JOIN PROYECTO1.TIPO_PREMIO TP
   ON TP.ID_TIPO_PREMIO = PM.FK_ID_TIPO_PREMIO
   INNER JOIN PROYECTO1.MUNDIAL M
   ON M.ID_MUNDIAL = PM.FK_ID_MUNDIAL
   WHERE PM.FK_ID_JUGADOR = @Id_jugador

   
	SELECT TIPOTARJETA, MINUTO , M.ANIO AS MUNDIAL, P.NOMBRE_EQUIPO1, P.NOMBRE_EQUIPO2
	FROM PROYECTO1.TARJETA T
	INNER JOIN PROYECTO1.PARTIDO P
	ON P.ID_PARTIDO = T.FK_ID_PARTIDO
	INNER JOIN PROYECTO1.MUNDIAL M
	ON M.ID_MUNDIAL = P.FK_ID_MUNDIAL
	where T.FK_JUGADOR_TARJETA = @Id_jugador

	SELECT C.MINUTO, j.NOMBRE_JUGADOR as Entro, @Jugador Sale, M.ANIO Mundial FROM PROYECTO1.CAMBIOS C
	inner join PROYECTO1.JUGADOR J
	on J.ID_JUGADOR = C.FK_JUGADOR_ENTRA
	inner join PROYECTO1.PARTIDO P
	on P.ID_PARTIDO = C.FK_ID_PARTIDO
	inner join PROYECTO1.MUNDIAL M
	on M.ID_MUNDIAL = P.FK_ID_MUNDIAL
	where C.FK_JUGADOR_SALE = @Id_jugador

GO