
SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_PREMIOS_MUNDIALES;
SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_TRESULTADOS_PARTIDO;
SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_POSICIONES_FINALES;
SELECT count(*) FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_JUGADOR;

SELECT DISTINCT PREMIO FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_PREMIOS_MUNDIALES;

SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.TIPO_PREMIO;
SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA;
SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO;

-- TIPO_PREMIO
INSERT INTO DB_BDD2PROYECTO1.PROYECTO1.TIPO_PREMIO(DESCRIPCION_PREMIO)
SELECT DISTINCT PREMIO FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_PREMIOS_MUNDIALES;

-- ETAPA
INSERT INTO DB_BDD2PROYECTO1.PROYECTO1.ETAPA(NOMBRE_ETAPA)
SELECT DISTINCT TEMP.ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_POSICIONES_FINALES AS TEMP WHERE MUNDIAL NOT IN ('Mundial 2022');

-- MUNDIAL
INSERT INTO DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL(ANIO, CAMPEON, ORGANIZADOR, SELECCIONES, PARTIDOS, GOLES)
SELECT CONVERT(INT, REPLACE(T1.MUNDIAL, 'Mundial ', '')), T1.CAMPEON, 'ORGANIZADOR', T2.SELECCIONES, T3.PARTIDOS, T4.GOLES
FROM
    (SELECT MUNDIAL, SELECCION AS CAMPEON FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_POSICIONES_FINALES WHERE POSICION = 1) T1
JOIN
    (SELECT MUNDIAL AS MUNDIAL, COUNT(SELECCION) AS SELECCIONES FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_POSICIONES_FINALES GROUP BY MUNDIAL) T2
ON
    (T1.MUNDIAL = T2.MUNDIAL)
JOIN
    (SELECT MUNDIAL AS MUNDIAL, COUNT(MUNDIAL) AS PARTIDOS FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_TRESULTADOS_PARTIDO GROUP BY MUNDIAL) T3
ON
    (T2.MUNDIAL = T3.MUNDIAL)
JOIN
    (SELECT MUNDIAL AS MUNDIAL, SUM(CONVERT(INT, GOLES)) AS GOLES FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_GOLEADORES_MUNDIAL GROUP BY MUNDIAL) T4
ON
    (T3.MUNDIAL = T4.MUNDIAL);


-- EQUIPO
INSERT INTO DB_BDD2PROYECTO1.PROYECTO1.EQUIPO(NOMBRE_EQUIPO)
SELECT DISTINCT SELECCION FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_POSICIONES_FINALES ORDER BY SELECCION ASC;

-- PARTIDO
INSERT INTO DB_BDD2PROYECTO1.PROYECTO1.PARTIDO(FK_ID_MUNDIAL, FK_ID_EQUIPO1, NOMBRE_EQUIPO1, FK_ID_EQUIPO2, NOMBRE_EQUIPO2)
SELECT
    (SELECT MU.ID_MUNDIAL FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL AS MU WHERE MU.ANIO=CONVERT(INT, REPLACE(PARTY.MUNDIAL, 'Mundial ', ''))),
    (SELECT EQ.ID_EQUIPO FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO AS EQ WHERE EQ.NOMBRE_EQUIPO=PARTY.EQUIPO1),PARTY.EQUIPO1,
    (SELECT EQ.ID_EQUIPO FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO AS EQ WHERE EQ.NOMBRE_EQUIPO=PARTY.EQUIPO2),PARTY.EQUIPO2
FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_TRESULTADOS_PARTIDO AS PARTY WHERE MUNDIAL NOT IN ('Mundia','Mundial 2022');

-- POSICIONES FINALES
INSERT INTO DB_BDD2PROYECTO1.PROYECTO1.POSICIONES_FINALES(POSICION, FK_ID_MUNDIAL, FK_ID_EQUIPO, FK_ID_ETAPA, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES)
SELECT
    CAST(TEMP.POSICION AS INT),
    (SELECT MU.ID_MUNDIAL FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL AS MU WHERE MU.ANIO=CONVERT(INT, REPLACE(TEMP.MUNDIAL, 'Mundial ', ''))),
    (SELECT EQ.ID_EQUIPO FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO AS EQ WHERE EQ.NOMBRE_EQUIPO=TEMP.SELECCION),
    (SELECT ET.ID_ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA AS ET WHERE ET.NOMBRE_ETAPA=TEMP.ETAPA),
    TEMP.PTS,TEMP.PJ,TEMP.PG,TEMP.PE,TEMP.PP,TEMP.GF,TEMP.GC,TEMP.DIF
FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_POSICIONES_FINALES AS TEMP WHERE MUNDIAL NOT IN ('Mundial 2022');









--- JUGADOR

INSERT INTO PROYECTO1.JUGADOR (NOMBRE_JUGADOR, FECHA_NACIMIENTO, LUGAR_NAC, FK_ID_POSICION, NUMERO_CAMISETA, ALTURA,
			APODO, WEB, LINK, FK_ID_EQUIPO, POSICION)
SELECT 
Nombre,CONVERT(DATETIME,REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
				REPLACE(FechaNac,'de','-'),
				'enero',
				'1'),'febrero','2'),'marzo','3'),'abril','4'),'mayo','5'),'junio','6'),'julio','7'),'agosto','8'),'septiembre','9'),'octubre','10')
				,'noviembre','11'),'diciembre','12'),105) AS FECHA,
	REPLACE(LugarNac,'_',',') lugarNac, POS.ID_POSICION, NoCamiseta, 
			CASE
                  WHEN LEN(altura) = 5
                     THEN REPLACE(altura,'mts','0')
                  ELSE  REPLACE(altura,'mts','')
             END AS altura, apodo, web, REPLACE(Link,'/jugadores/..','')as link, EQ.ID_EQUIPO, Posicion
FROM PROYECTO1.DATASET_JUGADOR as JUG
INNER JOIN PROYECTO1.POSICION AS POS
ON POS.NOMBRE_POSICION = JUG.Posicion
INNER JOIN PROYECTO1.EQUIPO EQ
ON EQ.NOMBRE_EQUIPO = REPLACE(seleccion,' ','')







-- RESULTADO
INSERT INTO DB_BDD2PROYECTO1.PROYECTO1.RESULTADO(FECHA, NO_PARTIDO, FK_ID_ETAPA, FK_ID_PARTIDO, GOLES_EQUIPO1, GOLES_EQUIPO2)
SELECT
    CAST(REPLACE(TEMP.FECHA, 'Fecha:', '') as date),
    0,
    (CASE
        WHEN (SELECT SUBSTRING(TEMP.ETAPA, 1, 8))='1raRonda'
				THEN (SELECT ET2.ID_ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA AS ET2 WHERE ET2.NOMBRE_ETAPA='Grupos 1ra Ronda')
        WHEN (SELECT SUBSTRING(TEMP.ETAPA, 1, 8))='2raRonda'
				THEN (SELECT ET2.ID_ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA AS ET2 WHERE ET2.NOMBRE_ETAPA='Grupos 2ra Ronda')
        WHEN (SELECT SUBSTRING(TEMP.ETAPA, 1, 8))='3erPuest '
				THEN (SELECT ET2.ID_ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA AS ET2 WHERE ET2.NOMBRE_ETAPA='Partido 3er Puesto')
        WHEN (SELECT SUBSTRING(TEMP.ETAPA, 1, 8))='Cuartos '
				THEN (SELECT ET2.ID_ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA AS ET2 WHERE ET2.NOMBRE_ETAPA='Cuartos de Final')
        WHEN (SELECT SUBSTRING(TEMP.ETAPA, 1, 8))='Final '
				THEN (SELECT ET2.ID_ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA AS ET2 WHERE ET2.NOMBRE_ETAPA='Final')
        WHEN (SELECT SUBSTRING(TEMP.ETAPA, 1, 8))='Octavos '
				THEN (SELECT ET2.ID_ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA AS ET2 WHERE ET2.NOMBRE_ETAPA='Octavos de Final')
        WHEN (SELECT SUBSTRING(TEMP.ETAPA, 1, 8))='RondaFin '
				THEN (SELECT ET2.ID_ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA AS ET2 WHERE ET2.NOMBRE_ETAPA='Final')
        WHEN (SELECT SUBSTRING(TEMP.ETAPA, 1, 8))='Semis '
				THEN (SELECT ET2.ID_ETAPA FROM DB_BDD2PROYECTO1.PROYECTO1.ETAPA AS ET2 WHERE ET2.NOMBRE_ETAPA='Semifinal')
		ELSE '1'
                END),
    (
        SELECT top 1 PAR.ID_PARTIDO FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL MUN, DB_BDD2PROYECTO1.PROYECTO1.PARTIDO PAR
        WHERE MUN.ID_MUNDIAL=PAR.FK_ID_MUNDIAL
        AND PAR.FK_ID_EQUIPO1=(SELECT EQU.ID_EQUIPO FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO EQU WHERE EQU.NOMBRE_EQUIPO=TEMP.EQUIPO1)
        AND PAR.FK_ID_EQUIPO2=(SELECT EQU.ID_EQUIPO FROM DB_BDD2PROYECTO1.PROYECTO1.EQUIPO EQU WHERE EQU.NOMBRE_EQUIPO=TEMP.EQUIPO2)
        AND MUN.ANIO=CONVERT(INT, REPLACE(TEMP.MUNDIAL, 'Mundial ', ''))
    )
    ,
    CAST((SELECT SUBSTRING(TEMP.RESULTADO, 1, 1)) AS INT),
    CAST((SELECT SUBSTRING(TEMP.RESULTADO, 3, 1)) AS INT)
FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_TRESULTADOS_PARTIDO AS TEMP WHERE TEMP.MUNDIAL NOT IN ('Mundia','Mundial 2022');

-- PREMIOS MUNDIAL
INSERT INTO DB_BDD2PROYECTO1.PROYECTO1.PREMIOS_MUNDIAL(FK_ID_MUNDIAL, FK_ID_TIPO_PREMIO, FK_ID_JUGADOR)
SELECT T1.ID_MUNDIAL, T3.ID_TIPO_PREMIO, T4.ID_JUGADOR
FROM
    (SELECT ID_MUNDIAL, ANIO FROM DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL) T1
JOIN
    (SELECT CONVERT(INT, REPLACE(MUNDIAL, 'Mundial ', '')) AS ANIO, PREMIO, JUGADOR, LINK FROM DB_BDD2PROYECTO1.PROYECTO1.DATASET_PREMIOS_MUNDIALES) T2
ON
    (T1.ANIO = T2.ANIO)
JOIN
    (SELECT ID_TIPO_PREMIO, DESCRIPCION_PREMIO FROM DB_BDD2PROYECTO1.PROYECTO1.TIPO_PREMIO) T3
ON
    (T3.DESCRIPCION_PREMIO = T2.PREMIO)
JOIN
    (SELECT ID_JUGADOR, NOMBRE_JUGADOR, LINK FROM DB_BDD2PROYECTO1.PROYECTO1.JUGADOR) T4
ON
    (T4.LINK = T2.LINK)



-- GOleadores

INSERT INTO PROYECTO1.GOLEADOR (GOLES, PARTIDOS, PROMEDIO, FK_ID_JUGADOR, FK_ID_MUNDIAL)
SELECT GOL.Goles, GOL.Partidos, Promedio_de_Gol/100 AS prom, JUG.ID_JUGADOR, MUN.ID_MUNDIAL
FROM PROYECTO1.DATASET_GOLEADOR_MUNDIAL GOL
INNER JOIN PROYECTO1.JUGADOR AS JUG
ON JUG.LINK = GOL.link
INNER JOIN PROYECTO1.MUNDIAL MUN
ON MUN.ANIO = REPLACE(GOL.Mundial,'Mundial ', '')
ORDER BY MUN.ANIO DESC , GOL.Goles DESC


--- ALINEACIONES

INSERT INTO PROYECTO1.ALINEACION(POSICION, CAMISETA, FK_ID_JUGADOR,ESTADO, FK_ID_PARTIDO)
SELECT JP.Pos, JP.Camiseta, J.ID_JUGADOR, JP.Estado, P.ID_PARTIDO  
FROM PROYECTO1.DATASET_JUGADORES_PARTIDO JP
INNER JOIN PROYECTO1.JUGADOR J
ON J.LINK = REPLACE(JP.linkJugador,'..','')
INNER JOIN PROYECTO1.PARTIDO P
ON P.NOMBRE_EQUIPO1 = JP.local AND P.NOMBRE_EQUIPO2 = JP.visitante
INNER JOIN PROYECTO1.MUNDIAL M
ON M.ANIO = REPLACE(JP.MundiaL,'Mundial ','')


--- TARJETAS 

INSERT INTO PROYECTO1.TARJETA (PAIS, FK_JUGADOR_TARJETA, TIPOTARJETA, MINUTO, FK_ID_PARTIDO)
SELECT Pais, J.ID_JUGADOR, CASE WHEN Tarjeta = '-' THEN 'roja' ELSE Tarjeta END, REPLACE(minuto,CHAR(39),'')
,p.ID_PARTIDO FROM PROYECTO1.DATASET_TARJETAS_PARTIDO T
inner join PROYECTO1.JUGADOR J
ON J.NOMBRE_JUGADOR = T.Jugador
INNER JOIN PROYECTO1.PARTIDO P
ON P.NOMBRE_EQUIPO1 = T.local AND P.NOMBRE_EQUIPO2 = T.visitante
INNER JOIN PROYECTO1.MUNDIAL M
ON M.ANIO = REPLACE(T.Mundia,'Mundial ','')


--- CAMBIOS

INSERT INTO PROYECTO1.CAMBIOS (PAIS, MINUTO, FK_JUGADOR_ENTRA, FK_JUGADOR_SALE, FK_ID_PARTIDO)

SELECT AUX.Pais, Aux.Minuto, Aux.Sale, JUG.ID_JUGADOR,Aux.idp  FROM (
SELECT  Pais, Replace(Minuto,'minuto','') Minuto,J.ID_JUGADOR as Sale, CP.Entra as Entra, p.ID_PARTIDO as idp
FROM PROYECTO1.DATASET_CAMBIOS_PARTIDO CP
INNER JOIN PROYECTO1.JUGADOR J
ON J.NOMBRE_JUGADOR = CP.Sale
INNER JOIN PROYECTO1.PARTIDO P
ON P.NOMBRE_EQUIPO1 = CP.local AND P.NOMBRE_EQUIPO2 = CP.visitante
INNER JOIN PROYECTO1.MUNDIAL M
ON M.ANIO = REPLACE(CP.Mundia,'Mundial ','')
) AS AUX
INNER JOIN PROYECTO1.JUGADOR AS JUG
ON JUG.NOMBRE_JUGADOR = AUX.Entra


----


SELECT * FROM PROYECTO1.DATASET_TARJETAS_PARTIDO T
INNER JOIN PROYECTO1.MUNDIAL M
ON M.ANIO = REPLACE(T.Mundia,'Mundial ','')
inner join PROYECTO1.JUGADOR J
ON J.NOMBRE_JUGADOR = T.Jugador
inner join PROYECTO1.PARTIDO P 
ON P.NOMBRE_EQUIPO1 = T.local and P.NOMBRE_EQUIPO2 = T.visitante