CREATE DATABASE DB_BDD2PROYECTO1;
USE DB_BDD2PROYECTO1;
CREATE SCHEMA PROYECTO1;

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.EQUIPO;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.EQUIPO(
    /* TABLA INCOMPLETA DEBE LLEVAR LOS DATOS DE EQUIPO
       PARA USAR EN TABLA DE RESULTADO*/
    ID_EQUIPO           INT NOT NULL IDENTITY,
    NOMBRE_EQUIPO       VARCHAR(250) NOT NULL DEFAULT '',

    PRIMARY KEY (ID_EQUIPO),
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL(
    /* INFORMACION GENERAL */
    ID_MUNDIAL          INT NOT NULL IDENTITY,
    ANIO                INT NOT NULL,
    CAMPEON             VARCHAR(250) NOT NULL DEFAULT '',
    ORGANIZADOR         VARCHAR(250) NOT NULL DEFAULT '',
    SELECCIONES         INT NOT NULL DEFAULT 0,
    PARTIDOS            INT NOT NULL DEFAULT 0,
    GOLES               INT NOT NULL DEFAULT 0,
    PROMEDIO_DE_GOL     DECIMAL NOT NULL DEFAULT 0.0,
    /* FALTA CALENDARIO, RESULTADOS Y PREMIOS */

    /* DATOS QUE SON VISIBLES PARA POSICIONES FINALES*/
    POS_FIN1            VARCHAR(250) NOT NULL DEFAULT '',
    POS_FIN2            VARCHAR(250) NOT NULL DEFAULT '',
    POS_FIN3            VARCHAR(250) NOT NULL DEFAULT '',
    /* FALTA VER TABLA COMPLETA */

    /* FALTA LA FASE FINAL CON SUS LLAVES Y RESULTADOS*/

    /* DATOS QUE SON VISIBLES PARA GOLEADORES */
    GOLEADOR1           VARCHAR(250) NOT NULL DEFAULT '',
    GOLES_GOLEADOR1     INT NOT NULL DEFAULT 0,
    GOLEADOR2           VARCHAR(250) NOT NULL DEFAULT '',
    GOLES_GOLEADOR2     INT NOT NULL DEFAULT 0,
    GOLEADOR3           VARCHAR(250) NOT NULL DEFAULT '',
    GOLES_GOLEADOR3     INT NOT NULL DEFAULT 0,
    /* FALTA VER TODOS */

    /* DATOS QUE SON VISIBLES DE LA FINAL */
    /* FALTA MEJOR TRAER EL ID DEL PARTIDO */

    /* FALTA SELECCIONES CLASIFICADAS */
    /* ES UNA RELACION DE UNO A MUCHOS: MUNDIAL 1-* SELECCIONES */

    /* FALTA GRUPOS Y PLANTELES */
    /* ES UNA RELACION DE MUCHOS A MUCHOS: GRUPOS *-* PLANTELES */

    PRIMARY KEY (ID_MUNDIAL),
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.ETAPA;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.ETAPA(
    /* AGRUPA LAS DIFERENTES ETAPAS QUE SE PUEDEN USAR EN LA TABLA DE RESULTADO */
    ID_ETAPA            INT NOT NULL IDENTITY,
    NOMBRE_ETAPA        VARCHAR(250) NOT NULL DEFAULT '',

    PRIMARY KEY (ID_ETAPA),
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.PARTIDO;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.PARTIDO(
    /* TABLA INCOMPLETA DEBE LLEVAR LOS DATOS DE PARTIDO */
    ID_PARTIDO          INT NOT NULL IDENTITY,
    FK_ID_EQUIPO1       INT NOT NULL,
    FK_ID_EQUIPO2       INT NOT NULL,
    RESULTADO           VARCHAR(250) NOT NULL DEFAULT '', 
    NOMBRE_EQUIPO1      VARCHAR(250) NOT NULL DEFAULT '',
    NOMBRE_EQUIPO2      VARCHAR(250) NOT NULL DEFAULT '',

    PRIMARY KEY (ID_PARTIDO),
    CONSTRAINT FK_ID_EQUIPO1 FOREIGN KEY (FK_ID_EQUIPO1) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.EQUIPO(ID_EQUIPO),
    CONSTRAINT FK_ID_EQUIPO2 FOREIGN KEY (FK_ID_EQUIPO2) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.EQUIPO(ID_EQUIPO)
        ON DELETE CASCADE ON UPDATE CASCADE,
);

ALTER TABLE DB_BDD2PROYECTO1.PROYECTO1.PARTIDO
ADD FK_ID_MUNDIAL INT NOT NULL;

ALTER TABLE DB_BDD2PROYECTO1.PROYECTO1.PARTIDO
ADD FOREIGN KEY (FK_ID_MUNDIAL) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL(ID_MUNDIAL);


DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.ALINEACION;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.ALINEACION(
    ID_ALINEACION          INT NOT NULL IDENTITY,
    POSICION                VARCHAR(50) NOT NULL,
    CAMISETA                VARCHAR(10) NOT NULL,
    FK_ID_JUGADOR                 INT NOT NULL,
    ESTADO                  VARCHAR(60) NOT NULL,
    FK_ID_PARTIDO       INT NOT NULL,
    PRIMARY KEY (ID_ALINEACION),
    CONSTRAINT FK_ID_PARTIDO FOREIGN KEY (FK_ID_PARTIDO) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.PARTIDO(ID_PARTIDO),
    CONSTRAINT FK_JUGADOR_ALINEACION
        FOREIGN KEY (FK_ID_JUGADOR) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.JUGADOR (ID_JUGADOR)
    ON DELETE CASCADE ON UPDATE CASCADE,
);


DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.CAMBIOS;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.CAMBIOS(
    ID_CAMBIO               INT NOT NULL IDENTITY,
    PAIS                    VARCHAR(50) NOT NULL,
    MINUTO                  VARCHAR(50) NOT NULL,
    ID_JUGADOR_SALE         INT NOT NULL,
    ID_JUGADOR_ENTRA        INT NOT NULL,
    FK_ID_PARTIDO           INT NOT NULL,
    PRIMARY KEY (ID_CAMBIO),
    CONSTRAINT FK_ID_PARTIDO_CAMBIO FOREIGN KEY (FK_ID_PARTIDO) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.PARTIDO(ID_PARTIDO),
    CONSTRAINT FK_JUGADOR_OUT
        FOREIGN KEY (FK_ID_JUGADOR) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.JUGADOR (ID_JUGADOR),
    CONSTRAINT FK_JUGADOR_IN
        FOREIGN KEY (FK_ID_JUGADOR) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.JUGADOR (ID_JUGADOR)
    ON DELETE CASCADE ON UPDATE CASCADE,
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.TARJETA;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.TARJETA(
    ID_TARJETA              INT NOT NULL IDENTITY,
    PAIS                    VARCHAR(50) NOT NULL,
    FK_JUGADOR_TARJETA      INT NOT NULL, 
    TIPOTARJETA             VARCHAR(50) NOT NULL,
    FK_ID_PARTIDO           INT NOT NULL,
    PRIMARY KEY (ID_CAMBIO),
    CONSTRAINT FK_ID_PARTIDO_TARJETA FOREIGN KEY (FK_ID_PARTIDO) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.PARTIDO(ID_PARTIDO),
    CONSTRAINT FK_JUGADOR_TARJETA
        FOREIGN KEY (FK_ID_JUGADOR) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.JUGADOR (ID_JUGADOR)
    ON DELETE CASCADE ON UPDATE CASCADE,
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.RESULTADO;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.RESULTADO(
    ID_RESULTADO        INT NOT NULL IDENTITY,
    FECHA               DATE NOT NULL,
    NO_PARTIDO          INT NOT NULL,
    FK_ID_ETAPA         INT NOT NULL,
    FK_ID_PARTIDO       INT NOT NULL,
    GOLES_EQUIPO1       INT NOT NULL,
    GOLES_EQUIPO2       INT NOT NULL,

    PRIMARY KEY (ID_RESULTADO),
    CONSTRAINT FK_ID_ETAPA FOREIGN KEY (FK_ID_ETAPA) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.ETAPA (ID_ETAPA)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_PARTIDO FOREIGN KEY (FK_ID_PARTIDO) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.PARTIDO (ID_PARTIDO)
        ON DELETE CASCADE ON UPDATE CASCADE,
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL_RESULTADO;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL_RESULTADO(
    ID_MUNDIAL_RESULTADO    INT NOT NULL IDENTITY,
    FK_ID_RESULTADO         INT NOT NULL,
    FK_ID_MUNDIAL           INT NOT NULL,

    PRIMARY KEY (ID_MUNDIAL_RESULTADO),
    CONSTRAINT FK_ID_RESULTADO
        FOREIGN KEY (FK_ID_RESULTADO) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.RESULTADO (ID_RESULTADO)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_MUNDIAL
        FOREIGN KEY (FK_ID_MUNDIAL) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL (ID_MUNDIAL)
        ON DELETE CASCADE ON UPDATE CASCADE,
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.POSICIONES_FINALES;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.POSICIONES_FINALES(
    NO_CORRELATIVO          INT NOT NULL IDENTITY,
    POSICION                INT NOT NULL,
    FK_ID_MUNDIAL           INT NOT NULL,
    FK_ID_EQUIPO            INT NOT NULL,
    FK_ID_ETAPA             INT NOT NULL,
    PUNTOS                  INT NOT NULL,
    PARTIDOS_JUGADOS        INT NOT NULL,
    PARTIDOS_GANADOS        INT NOT NULL,
    PARTIDOS_EMPATADOS      INT NOT NULL,
    PARTIDOS_PERDIDOS       INT NOT NULL,
    GOLES_FAVOR             INT NOT NULL,
    GOLES_CONTRA            INT NOT NULL,
    DIFERENCIA_GOLES        INT NOT NULL,

    PRIMARY KEY (NO_CORRELATIVO),
    CONSTRAINT FK_ID_MUNDIAL_POS
        FOREIGN KEY (FK_ID_MUNDIAL) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL (ID_MUNDIAL)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_EQUIPO
        FOREIGN KEY (FK_ID_EQUIPO) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.EQUIPO (ID_EQUIPO)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_ETAPA_POS
        FOREIGN KEY (FK_ID_ETAPA) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.ETAPA (ID_ETAPA)
        ON DELETE CASCADE ON UPDATE CASCADE,
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.TIPO_PREMIO;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.TIPO_PREMIO(
    ID_TIPO_PREMIO          INT NOT NULL IDENTITY,    
    DESCRIPCION_PREMIO      VARCHAR(30) NOT NULL DEFAULT '',
    PRIMARY KEY (ID_TIPO_PREMIO),
);

/*
SELECT * FROM DB_BDD2PROYECTO1.PROYECTO1.TIPO_PREMIO;
INSERT INTO DB_BDD2PROYECTO1.PROYECTO1.TIPO_PREMIO(DESCRIPCION_PREMIO)
    VALUES('Balón de Oro'),
            ('Balón de Plata'),
            ('Balón de Bronce'),
            ('Botín de Oro'),
            ('Botín de Plata'),
            ('Botín de Bronce'),
            ('Guante de Oro'),
            ('Mejor Jugador Joven'),
            ('FIFA Fair Play'),
            ('Equipo Más Entretenido');
*/

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.PREMIOS_MUNDIAL;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.PREMIOS_MUNDIAL(
    NO_CORRELATIVO          INT NOT NULL IDENTITY,
    FK_ID_MUNDIAL           INT NOT NULL,
    FK_ID_TIPO_PREMIO       INT NOT NULL,
    FK_ID_JUGADOR           INT NOT NULL,

    PRIMARY KEY (NO_CORRELATIVO),
    CONSTRAINT FK_ID_MUNDIAL_PREMIO
        FOREIGN KEY (FK_ID_MUNDIAL) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL (ID_MUNDIAL)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_TIPO_PREMIO_0
        FOREIGN KEY (FK_ID_TIPO_PREMIO) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.TIPO_PREMIO (ID_TIPO_PREMIO)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_JUGADOR_PREMIO
        FOREIGN KEY (FK_ID_JUGADOR) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.JUGADOR (ID_JUGADOR)
        ON DELETE CASCADE ON UPDATE CASCADE,
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.EQUIPO_IDEAL;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.EQUIPO_IDEAL(
    ID_SELECCIONADO         INT NOT NULL IDENTITY,
    FK_ID_EQUIPO            INT NOT NULL,
    FK_ID_JUGADOR           INT NOT NULL,
    FK_ID_POSICION          INT NOT NULL,

    PRIMARY KEY (ID_SELECCIONADO),
    CONSTRAINT FK_ID_EQUIPO_IDEAL
        FOREIGN KEY (FK_ID_EQUIPO) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.EQUIPO (ID_EQUIPO)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_JUGADOR_IDEAL
        FOREIGN KEY (FK_ID_JUGADOR) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.JUGADOR (ID_JUGADOR)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_POSICION
        FOREIGN KEY (FK_ID_POSICION) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.POSICION (ID_POSICION)
        ON DELETE CASCADE ON UPDATE CASCADE,
);


DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.POSICION;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.POSICION(
    ID_POSICION            INT NOT NULL IDENTITY,
    NOMBRE_POSICION        VARCHAR(250) NOT NULL DEFAULT '',
    PRIMARY KEY (ID_POSICION),
);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.JUGADOR;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.JUGADOR(
    ID_JUGADOR           INT NOT NULL IDENTITY,
    NOMBRE_JUGADOR       VARCHAR(250) NOT NULL DEFAULT '',
    FECHA_NACIMIENTO     VARCHAR(250) NOT NULL,
    LUGAR_NAC             VARCHAR(250) NOT NULL,
    POSICION             VARCHAR(250) NOT NULL,
    NOCAMISETA           VARCHAR(250) NOT NULL,
    ALTURA               VARCHAR(250) NOT NULL,
    APODO                VARCHAR(250) NOT NULL,
    WEB                  VARCHAR(250) NOT NULL,
    FK_ID_EQUIPO         INT NOT NULL,
    FK_ID_POSICION       INT NOT NULL,
    PRIMARY KEY (ID_JUGADOR),
    CONSTRAINT FK_JUG_EQUIPO
    FOREIGN KEY (FK_ID_EQUIPO) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.EQUIPO(ID_EQUIPO)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_JUG_POS
    FOREIGN KEY (FK_ID_POSICION) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.POSICION(ID_POSICION)
    ON DELETE CASCADE ON UPDATE CASCADE

);

DROP TABLE IF EXISTS DB_BDD2PROYECTO1.PROYECTO1.GOLEADOR;
CREATE TABLE DB_BDD2PROYECTO1.PROYECTO1.GOLEADOR(
    ID_GOLEADOR          INT NOT NULL IDENTITY,
    GOLES                INT NOT NULL DEFAULT 0, 
    PARTIDOS             INT NOT NULL DEFAULT 0, 
    PROMEDIO             DECIMAL NOT NULL, 
    FK_ID_JUGADOR        INT NOT NULL, 
    FK_ID_MUNDIAL        INT NOT NULL, 
    PRIMARY KEY (ID_GOLEADOR),
    CONSTRAINT FK_GOL_JUG 
    FOREIGN KEY (FK_ID_JUGADOR) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.JUGADOR(ID_JUGADOR)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_GOL_MUNDIAL
    FOREIGN KEY (FK_ID_MUNDIAL) REFERENCES DB_BDD2PROYECTO1.PROYECTO1.MUNDIAL(ID_MUNDIAL)
    ON DELETE CASCADE ON UPDATE CASCADE
);

