--- Inciso A

BACKUP DATABASE DB_BDD2PROYECTO1 TO DISK = '/var/opt/mssql/data/DB_BDD2PROYECTO1.bak'
GO


-- Inciso B


use DB_BDD2PROYECTO1 EXEC sp_changedbowner 'sa';


DBCC SQLPERF (LOGSPACE);
GO

SELECT name FROM sys.master_files WHERE type_desc = 'LOG'

ALTER DATABASE DB_BDD2PROYECTO1
SET RECOVERY SIMPLE WITH NO_WAIT
GO
DBCC SHRINKFILE (DB_BDD2PROYECTO1_log, 1)
GO
ALTER DATABASE DB_BDD2PROYECTO1
SET RECOVERY FULL WITH NO_WAIT
GO



--- Inciso C

SELECT  OBJECT_NAME(IDX.OBJECT_ID) AS Table_Name, 
IDX.name AS Index_Name, 
IDXPS.index_type_desc AS Index_Type, 
IDXPS.avg_fragmentation_in_percent  Fragmentation_Percentage
FROM sys.dm_db_index_physical_stats(DB_ID(), NULL, NULL, NULL, NULL) IDXPS 
INNER JOIN sys.indexes IDX  ON IDX.object_id = IDXPS.object_id 
AND IDX.index_id = IDXPS.index_id 
ORDER BY Fragmentation_Percentage DESC



WITH INDICES (BD, INDICETIPO, FRAGMENTACION, INDICE, TABLA)
AS (
SELECT DBS.NAME BASEDEDATOS, PS.INDEX_TYPE_DESC, PS.AVG_FRAGMENTATION_IN_PERCENT,
IND.NAME INDICE, TAB.NAME TABLA
FROM
SYS.DM_DB_INDEX_PHYSICAL_STATS (DB_ID(), NULL, NULL, NULL, NULL) PS
INNER JOIN SYS.DATABASES DBS
ON PS.DATABASE_ID = DBS.DATABASE_ID
INNER JOIN SYS.INDEXES IND
ON PS.OBJECT_ID = IND.OBJECT_ID
INNER JOIN SYS.TABLES TAB
ON TAB.OBJECT_ID = IND.OBJECT_ID
WHERE IND.NAME IS NOT NULL AND PS.INDEX_ID = IND.INDEX_ID
AND PS.AVG_FRAGMENTATION_IN_PERCENT > 0)
SELECT DISTINCT 
  CASE
 WHEN FRAGMENTACION > 5 AND FRAGMENTACION <= 30 THEN 'ALTER INDEX ' + INDICE + ' ON ' + TABLA + ' REORGANIZE'
  WHEN FRAGMENTACION > 30 THEN 'ALTER INDEX ' + INDICE + ' ON ' + TABLA + ' REBUILD'
 END QUERY, FRAGMENTACION, BD, INDICE, TABLA
FROM (SELECT FRAGMENTACION, INDICE, TABLA, BD FROM INDICES
  WHERE FRAGMENTACION > 5) A
ORDER BY FRAGMENTACION DESC


ALTER INDEX REBUILD WITH (ONLINE = ON)


--- Paginacion //
Select * from PROYECTO1.JUGADOR
Order By ID_JUGADOR
OFFSET (1 - 1) * 5 ROWS
FETCH NEXT 5 ROWS ONLY;

Select * from PROYECTO1.JUGADOR
Order By ID_JUGADOR
OFFSET (2 - 1) * 5 ROWS
FETCH NEXT 5 ROWS ONLY

Select * from PROYECTO1.JUGADOR
Order By ID_JUGADOR
OFFSET (3 - 1) * 5 ROWS
FETCH NEXT 5 ROWS ONLY
